name: Code review

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run all linting tools
        run: yarn lint:all
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
